# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch :

jobs:
  deploy:

    runs-on: [self-hosted, staging, backend]

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name : 'Deploy Node Backend'
      run: |
        npm ci
        echo "${{ secrets.ENV_FILE_STAGING }}" > .env
        export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.13.0/bin
        pm2 restart backend
        
    - name: 'Cleanups logs an cache'
      run: |
        sudo rm -rf /var/log/journal/
        sudo rm -rf /home/ubuntu/.pm2/logs/
        sudo rm -rf ~/.cache/
